version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URI=mongodb://mongo:27017/job-portal
      - JWT_SECRET=supersecurejwtkey
      - JWT_REFRESH_SECRET=supersecurejwtrefreshkey
      - JWT_EXPIRES_IN=1d
      - JWT_REFRESH_EXPIRES_IN=14d
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
